dry-dock/u14all

Dockerfile, install.sh, shippable.yml, version/cassandra_2_1.sh, version/couchdb_1_6.sh, version/neo4j_2_2.sh, version/rethinkdb_2_0.sh, version/riak_latest.sh
fixes https://github.com/dry-dock/u14all/issues/1
=> added services to ubuntu 14.04 image

install.sh, neo4j-server.properties
fixes https://github.com/dry-dock/u14all/issues/3
=> added neo4j-server properties to allow clients to connect without authentication

shippable.yml
Fixes https://github.com/dry-dock/u14all/issues/5
=> updates yml format

shippable.yml, test/_couchdb.sh, test/_neo4j.sh, test/_rethinkdb.sh, test/_riak.sh, test/function_start_generic.sh, version/cassandra_2_1.sh
Fixes https://github.com/dry-dock/u14all/issues/7
=> Add test for all services

README.md
Fixes https://github.com/dry-dock/u14all/issues/9
=> updates README with list of available services

install.sh, test/_elasticsearch.sh, test/_memcached.sh, test/_mongo.sh, test/_mysql.sh, test/_postgres.sh, test/_rabbitmq.sh, test/_redis.sh, test/_selenium.sh
=> create required dir for neo4j 

test/_elasticsearch.sh
=> update elasticsearch start script 

test/_elasticsearch.sh, test/_neo4j.sh, test/_selenium.sh
=> update start and stop scripts 

version/selenium_2_53.sh
=> Removing google chrome from updation list

Dockerfile, build.sh
=> use prod tag to build image 

Dockerfile, build.sh
=> use tag from resources to build image 

Dockerfile
=> undo removing tmp 

version/postgres_9_6.sh
=> Add postgis

version/memcached_1_4.sh
=> Add libsasl2-dev

README.md, services/selenium.sh, test/_selenium.sh, version/selenium.sh
https://github.com/dry-dock/u14all/issues/31
=> update selenium version to 3.4.0

services/postgres.sh, services/postgres_env.sh
from https://github.com/dry-dock/u14all/issues/33
=> create and source postgres_env files

services/cassandra.sh, services/cassandra_env.sh, services/couchdb.sh, services/couchdb_env.sh, services/elasticsearch.sh, services/elasticsearch_env.sh, services/memcached.sh, services/memcached_env.sh, services/mongodb.sh, services/mongodb_env.sh, services/mysql.sh, services/mysql_env.sh, services/neo4j.sh, services/neo4j_env.sh, services/rabbitmq.sh, services/rabbitmq_env.sh, services/redis.sh, services/redis_env.sh, services/rethinkdb.sh, services/rethinkdb_env.sh, services/selenium.sh, services/selenium_env.sh
fixes https://github.com/dry-dock/u14all/issues/33
=> create and source the env files of all services

version/cassandra_3_11.sh, version/cassandra_3_9.sh
fixes https://github.com/dry-dock/u14all/issues/36
=> update cassandra from 3.9 to 3.11

version/elasticsearch_5_5_0.sh
fixes https://github.com/dry-dock/u14all/issues/42
verified on my local system by starting,stopping elasticsearch and also the version of elasticsearch
=> update elasticsearch from 5.1.2 to 5.5.0

version/memcached_1_4_39.sh
fixes https://github.com/dry-dock/u14all/issues/40
verified on local system by stating,stopping elasticsearch and the version of elasticsearch
=> update memcached 1.4.32 to 1.4.39

version/mongodb_3_4_6.sh
fixes https://github.com/dry-dock/u14all/issues/43
verified on my local system by starting,stopping mongodb and version of mongodb
=> update mongodb 3.4 to 3.4.6

version/redis_3_2_9.sh
fixes https://github.com/dry-dock/u14all/issues/47
verified on the local system by starting,stopping redis and the version
=> update redis to 3.2 to 3.2.9

services/couchdb_env.sh, services/rabbitmq.sh, test/_rabbitmq.sh
from https://github.com/dry-dock/u14all/issues/57
=> add shutdown command for rabbitmq

version/sqllite_3.sh, version/sqllite_3_19_2.sh
fixes https://github.com/dry-dock/u14all/issues/49
verified the version of sqllite on my local system
=> update sqlite3 from 3 to 3.19.2

version/mysql_5_6.sh
https://github.com/dry-dock/u14all/issues/72
=> add soft link to correct mysql socket pointer

services/mysql.sh, version/mysql_5_6.sh
https://github.com/dry-dock/u14all/issues/72
=> create symlink for mysql.lock after booting mysql service 

version/elasticsearch_5_5_1.sh, version/mongodb_3_4_6.sh
https://github.com/dry-dock/u14all/issues/72
solution as per https://github.com/tianon/gosu/issues/17#issuecomment-203074866
=> use alternate gpg path to fix u14 build error

version/riak_2_2_3.sh
https://github.com/dry-dock/u14all/issues/77
fixes failing build for u14all
=> use alternate installation method for riak

services/neo4j.sh, services/neo4j_env.sh, test/_neo4j.sh, version/neo4j_3_2_6.sh
https://github.com/dry-dock/u14all/issues/80
=> installs neo4j using tarball

services/selenium_env.sh
https://github.com/dry-dock/u14all/issues/101
=> fix selenium start script

services/postgres_env.sh, version/redis_4_0_7.sh
https://github.com/dry-dock/u14all/issues/118
update redis-server minor version to fix failing build
and sets postgres env var
=> set postgres env var for shippable service

version/sqlite_3_22_0.sh
https://github.com/dry-dock/u14all/issues/118
able to build image locally after this. added docs task to track the change
=> update sqlite3 to fix breaking build

services/mysql.sh, services/postgres.sh
https://github.com/dry-dock/u14all/issues/122
https://github.com/dry-dock/u14all/issues/131
=> postgres and mysql should fail with error if binary is not found

version/redis_4_0.sh
https://github.com/dry-dock/u14all/issues/131
https://github.com/dry-dock/u14all/issues/122
=> update redis version to fix breaking build

version/selenium.sh
https://github.com/dry-dock/u14all/issues/134
=> DEV install latest chrome_driver release which is compatible with stable chrome version

version/mysql_5_7_21.sh
https://github.com/dry-dock/u14all/issues/140
=> Update and rename mysql_5_7_20.sh to mysql_5_7_21.sh

install.sh, version/elasticsearch_6_2_4.sh
https://github.com/dry-dock/u14all/issues/149
=> Update elastic search version 6.2.3 to 6.2.4

version/mongodb_3_6_4.sh
https://github.com/dry-dock/u14all/issues/153
=> Update mongodb version 3.6.3 to 3.6.4

version/neo4j_3_3_5.sh
https://github.com/dry-dock/u14all/issues/155
=> Update neo4j version 3.3.4 to 3.3.5

services/selenium_env.sh
https://github.com/dry-dock/u14all/issues/162
=> update selenium binary 3.8.1 to 3.11.0

version/mysql_5_7_22.sh
https://github.com/dry-dock/u14all/issues/159
=> Update and rename mysql_5_7_21.sh to mysql_5_7_22.sh

install.sh
https://github.com/Shippable/pm/issues/11008
=> adding pycrypto package

README.md, services/selenium_env.sh, version/elasticsearch_6_3_1.sh, version/memcached_1_5_9.sh, version/mongodb_4_0_0.sh, version/neo4j_3_3_6.sh, version/selenium3_13_0.sh
https://github.com/dry-dock/u14all/issues/177
https://github.com/dry-dock/u14all/issues/179
https://github.com/dry-dock/u14all/issues/180
https://github.com/dry-dock/u14all/issues/181
https://github.com/dry-dock/u14all/issues/182
=> update the latest versions in u14all image

README.md, version/elasticsearch_6_4_2.sh, version/memcached_1_5_11.sh, version/mongodb_4_0_3.sh
https://github.com/dry-dock/u14all/issues/221
https://github.com/dry-dock/u14all/issues/220
https://github.com/dry-dock/u14all/issues/219
=> update latest version for u14all image

README.md, version/elasticsearch_6_4_2.sh, version/mysql_5_7_24.sh, version/neo4j_3_3_8.sh
https://github.com/Shippable/pm/issues/11522
=> update latest versions for u14all image

README.md
https://github.com/Shippable/pm/issues/11547
=> adding Dockerhub/drydock link git repo u14all

version/redis_5_0.sh
https://github.com/Shippable/pm/issues/11522
=> update latest redis version for u14all image 

README.md
https://github.com/Shippable/pm/issues/11522
=> Update README.md file for u14all image

install.sh
https://github.com/Shippable/pm/issues/11739
=> update postgres version for u14all image
